apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xrrj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xrrj
    app.kubernetes.io/part-of: ci1t-830-0035-app
  name: devfile-sample-xrrj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xrrj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xrrj
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0035-tenant/ci1t-830-0035-app/devfile-sample-xrrj@sha256:00dd0bfdd90aa31b437a07ba93c24649e98bf4467ca03f19ae9303cea928be1c
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
